# course-related
COURSE_LENGTH_Y = 2
COURSE_LENGTH_X = 3

TRAIN_FACTOR = 6
TRAINING_TRIAL_LIMIT = ((COURSE_LENGTH_Y - 1) + (COURSE_LENGTH_X - 1)) * TRAIN_FACTOR
TESTING_TRIAL_LIMIT = (COURSE_LENGTH_Y - 1) + (COURSE_LENGTH_X - 1)

# hyper-parameters
ALPHA = 0.1
EPSILON = 1
GAMMA = 0.9
