# course related
MAX_COURSE_LENGTH = 10
TRAIN_FACTOR = 5

# hyper-parameters
EPOCHS = 300_000
ALPHA = 0.1
EPSILON = 1
GAMMA = 0.9999

# learning-methods
LEARNING_METHODS_LIST = ['1', '2', '3', '4']
LEARNING_METHODS_SET = set(LEARNING_METHODS_LIST)